apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bigquerytables.mahdi.dev 
spec:
  group: mahdi.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                project:  
                  type: string
                dataset:
                  type: string
                tableName:
                  type: string
              required:
                - type
                - dataset
  scope: Namespaced
  names:
    plural: bigquerytables
    singular: bigquerytable 
    kind: BigQueryTable 
    shortNames:
      - bqt